#!/usr/bin/env python3
"""
Merge litellm_config_base.yaml and models.yaml into litellm_config.yaml

This script:
1. Reads the base config (litellm_config_base.yaml)
2. Reads the models list (models.yaml)
3. Merges them into a single litellm_config.yaml

Usage:
  python3 scripts/merge_config.py
"""
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("❌ PyYAML not installed. Installing...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pyyaml"])
    import yaml


def main():
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent

    base_config_path = project_root / "litellm_config_base.yaml"
    models_path = project_root / "models.yaml"
    output_path = project_root / "litellm_config.yaml"

    # Check files exist
    if not base_config_path.exists():
        print(f"❌ Base config not found: {base_config_path}")
        sys.exit(1)

    if not models_path.exists():
        print(f"❌ Models file not found: {models_path}")
        print("   Run: python3 scripts/fetch_models.py first")
        sys.exit(1)

    # Load base config
    with open(base_config_path, "r") as f:
        base_config = yaml.safe_load(f) or {}

    # Load models
    with open(models_path, "r") as f:
        models_data = yaml.safe_load(f) or {}

    # Merge: add model_list from models.yaml to base config
    base_config["model_list"] = models_data.get("model_list", [])

    # Write merged config
    with open(output_path, "w") as f:
        # Add header comment
        f.write("# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY\n")
        f.write("# Generated by: python3 scripts/merge_config.py\n")
        f.write("# Edit litellm_config_base.yaml and models.yaml instead\n\n")
        yaml.dump(base_config, f, default_flow_style=False, sort_keys=False, indent=2)

    print(f"✅ Merged config written to {output_path}")
    print(f"   Base config: {base_config_path}")
    print(f"   Models: {models_path}")
    print(f"   Model count: {len(base_config.get('model_list', []))}")


if __name__ == "__main__":
    main()
